### ISSUE TITLE
Please provide healthy check and bind it to your notification system

### ISSUE THREAD

**Issue by seymurfarziyev** [oktant/nosy-email#2]
Hi guys!

Please help us to check status of your rest endpoints regularly, ideally please check their healthy status in an automated way, because once rest APIs from your site stops working we are getting blocked accordingly.

Thanks a lot! :)

Cheers,
DevHQ dev team

**Comment by ghost** [comment]
Closed and moved to https://github.com/notification-system/nosy-email/issues/7
