### ISSUE TITLE
Please provide healthy check and bind it to your notification system

### ISSUE THREAD

**Issue by ghost** [oktant/nosy-email#7]
In order to check status of your rest endpoints regularly, ideally please check their healthy status in an automated way, because once rest APIs from your site stops working we are getting blocked accordingly.

**Comment by ghost** [comment]
Fixed in the code and Test environment, please provide me with a timeslot to deploy in QA @seymurfarziyev

**Comment by seymurfarziyev** [comment]
We will replay our testings with Nosy next Monday, so feel free deploy to QA. Just wondering, how will you get notified (per email or notification system, slack whatever ?) when any of your services is down or performs slowly ?
Thanks a lot!

**Comment by ghost** [comment]
we will get grafana soon in our QA environment, you can follow the enhancement here:
https://github.com/notification-system/nosy-deployment/issues/4
